# Generated by Django 5.2 on 2025-05-30 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='administrador',
            name='idAdministrador',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='seiMoradores',
            field=models.BooleanField(default=False),
        ),
    ]
