# Generated by Django 5.2.1 on 2025-06-13 15:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Administrador',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='distrito',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='abastecimentoAgua',
            field=models.CharField(blank=True, choices=[('REDE GERAL DE DISTRIBUIÇÃO', 'REDE GERAL DE DISTRIBUIÇÃO'), ('POÇO PROFUNDO OU ARTESIANO', 'POÇO PROFUNDO OU ARTESIANO'), ('POÇO RASO, FREÁTICO OU CACIMBA', 'POÇO RASO, FREÁTICO OU CACIMBA'), ('FONTE, NASCENTE OU MINA', 'FONTE, NASCENTE OU MINA'), ('CARRO-PIPA', 'CARRO-PIPA'), ('ÁGUA DA CHUVA ARMAZENADA', 'ÁGUA DA CHUVA ARMAZENADA'), ('RIOS, AÇUDES, CÓRREGOS, LAGOS E IGARAPÉS', 'RIOS, AÇUDES, CÓRREGOS, LAGOS E IGARAPÉS'), ('OUTRA', 'OUTRA')], null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='acessoRedeAgua',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='aguaChega',
            field=models.CharField(blank=True, choices=[('ENCANADA ATÉ DENTRO DA CASA, APARTAMENTO OU HABITAÇÃO', 'ENCANADA ATÉ DENTRO DA CASA, APARTAMENTO OU HABITAÇÃO'), ('ENCANADA, MAS APENAS NO TERRENO', 'ENCANADA, MAS APENAS NO TERRENO'), ('NÃO CHEGA ENCANADA', 'NÃO CHEGA ENCANADA')], null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='cep',
            field=models.CharField(default='00000-000', max_length=10),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='cidade',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='esgotoFim',
            field=models.CharField(blank=True, choices=[('REDE GERAL OU PLUVIAL', 'REDE GERAL OU PLUVIAL'), ('FOSSA SÉPTICA OU FOSSA FILTRO LIGADA À REDE', 'FOSSA SÉPTICA OU FOSSA FILTRO LIGADA À REDE'), ('FOSSA SÉPTICA OU FOSSA FILTRO NÃO LIGADA À REDE', 'FOSSA SÉPTICA OU FOSSA FILTRO NÃO LIGADA À REDE'), ('FOSSA RUDIMENTAR OU BURACO', 'FOSSA RUDIMENTAR OU BURACO'), ('VALA', 'VALA'), ('RIO, LAGO, CÓRREGO OU MAR', 'RIO, LAGO, CÓRREGO OU MAR'), ('OUTRA FORMA', 'OUTRA FORMA')], null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='esgotoSBFim',
            field=models.CharField(blank=True, choices=[('REDE GERAL OU PLUVIAL', 'REDE GERAL OU PLUVIAL'), ('FOSSA SÉPTICA OU FOSSA FILTRO LIGADA À REDE', 'FOSSA SÉPTICA OU FOSSA FILTRO LIGADA À REDE'), ('FOSSA SÉPTICA OU FOSSA FILTRO NÃO LIGADA À REDE', 'FOSSA SÉPTICA OU FOSSA FILTRO NÃO LIGADA À REDE'), ('FOSSA RUDIMENTAR OU BURACO', 'FOSSA RUDIMENTAR OU BURACO'), ('VALA', 'VALA'), ('RIO, LAGO, CÓRREGO OU MAR', 'RIO, LAGO, CÓRREGO OU MAR'), ('OUTRA FORMA', 'OUTRA FORMA')], null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='lixoDomicilio',
            field=models.CharField(blank=True, choices=[('COLETADO NO DOMICÍLIO POR SERVIÇO DE LIMPEZA', 'COLETADO NO DOMICÍLIO POR SERVIÇO DE LIMPEZA'), ('DEPOSITADO EM CAÇAMBA DE SERVIÇO DE LIMPEZA', 'DEPOSITADO EM CAÇAMBA DE SERVIÇO DE LIMPEZA'), ('QUEIMADO NA PROPRIEDADE', 'QUEIMADO NA PROPRIEDADE'), ('ENTERRADO NA PROPRIEDADE', 'ENTERRADO NA PROPRIEDADE'), ('JOGADO EM TERRENO BALDIO, ENCOSTA OU ÁREA PÚBLICA', 'JOGADO EM TERRENO BALDIO, ENCOSTA OU ÁREA PÚBLICA'), ('OUTRO DESTINO', 'OUTRO DESTINO')], null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='qtdCriancas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='qtdMoradores',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='quantosbanheirosUsoExclusivo',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='utilizaBanheiroUsoComumMais',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='utilizaSanitarioBuracoDejecoes',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='SobrenomeFalecido',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='contatoCpf',
            field=models.CharField(blank=True, max_length=11, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='contatoEmail',
            field=models.CharField(blank=True, max_length=320, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='contatoNome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='contatoNumero',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='contatoTelefone',
            field=models.CharField(blank=True, choices=[('FIXO', 'FIXO'), ('MÓVEL', 'MÓVEL')], null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='corOuRaca',
            field=models.CharField(blank=True, choices=[('BRANCA', 'BRANCA'), ('PRETA', 'PRETA'), ('AMARELA', 'AMARELA'), ('PARDA', 'PARDA'), ('INDÍGENA', 'INDÍGENA')], null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='data_Nascimento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Morador', to='app.domicilio'),
        ),
        migrations.AddField(
            model_name='morador',
            name='etnia1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='etnia2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='faixaRendimento',
            field=models.CharField(blank=True, choices=[('VALOR EM DINHEIRO, PRODUTOS OU MERCADORIAS', ' VALOR EM DINHEIRO, PRODUTOS OU MERCADORIAS'), ('OUTRA FORMA (MORADIA, ALIMENTAÇÃO, TREINAMENTO ETC.)', 'OUTRA FORMA (MORADIA, ALIMENTAÇÃO, TREINAMENTO ETC.)'), ('NÃO TEM', 'NÃO TEM')], null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='falaLinguaIndigenaDomicilio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='falaPortuguesDomicilio',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='idadePessoaFalecida',
            field=models.CharField(blank=True, choices=[('FALECEU COM UM ANO OU MAIS DE IDADE', 'FALECEU COM UM ANO OU MAIS DE IDADE'), ('FALECEU COM MENOS DE UM ANO DE IDADE', 'FALECEU COM MENOS DE UM ANO DE IDADE')], null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='janeiro2019AJulho2025FaleceuPessoa',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='linguaIndigena1',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='linguaIndigena2',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='linguaIndigena3',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='mesAnoFalecimento',
            field=models.CharField(blank=True, choices=[('JULHO 2022', 'JULHO 2022'), ('JUNHO 2022', 'JUNHO 2022'), ('MAIO 2022', 'MAIO 2022'), ('MARÇO 2019', 'MARÇO 2019'), ('FEVEREIRO 2019', 'FEVEREIRO 2019'), ('JANEIRO 2019', 'JANEIRO 2019')], null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='nomeFalecido',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='nomeOutroMorador',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='nomeSuaComunidade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='quantosAnosAoFalecer',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='quantosMesesAoFalecer',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='quemPrestouInformacoesPessoa',
            field=models.CharField(blank=True, choices=[('A PRÓPRIA PESSOA', 'A PRÓPRIA PESSOA'), ('OUTRO MORADOR', 'OUTRO MORADOR'), ('NÃO MORADOR', 'NÃO MORADOR')], null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='registroCivilAteCincoAnos',
            field=models.CharField(blank=True, choices=[('DO CARTÓRIO', 'DO CARTÓRIO'), ('REGISTRO ADMINISTRATIVO DE NASCIMENTO INDÍGENA (RANI)', 'REGISTRO ADMINISTRATIVO DE NASCIMENTO INDÍGENA (RANI)'), ('NÃO TEM', 'NÃO TEM'), ('NÃO SABE', 'NÃO SABE')], null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='relacaoConvivencia',
            field=models.CharField(blank=True, choices=[('PESSOA RESPONSAVEL PELO DOMICILIO', 'PESSOA RESPONSAVEL PELO DOMICILIO'), ('CONJUGE OU COMPANHEIRO(A) DE SEXO DIFERENTE', 'CONJUGE OU COMPANHEIRO(A) DE SEXO DIFERENTE'), ('CONJUGE OU COMPANHEIRO(A) DO MESMO SEXO', 'CONJUGUE OU COMPANHEIRO(A) DO MESMO SEXO'), ('FILHO(A) DO RESPONSAVEL E DO CONJUGE', 'FILHO(A) DO RESPONSAVEL E DO CONJUGE'), ('FILHO(A) SOMENTE DO RESPONSAVEL', 'FILHO(A) SOMENTE DO RESPONSAVEL'), ('ENTEADO(A)', 'ENTEADO(A)'), ('GENRO OU NORA', 'GENRO OU NORA'), ('PAI, MAE, PADRASTO OU MADRASTA', 'PAI, MAE, PADRASTO OU MADRASTA'), ('SOGRO(A)', 'SOGRO(A)'), ('NETO(A)', 'NETO(A)'), ('BISNETO(A)', 'BISNETO(A)'), ('IRMAO OU IRMA', 'IRMAO OU IRMA'), ('AVO OU AVO', 'AVO OU AVO'), ('OUTRO PARENTE', 'OUTRO PARENTE'), ('AGREGADO(A)', 'AGREGADO(A)'), ('CONVIVENTE', 'CONVIVENTE'), ('PENSIONISTA', 'PENSIONISTA'), ('EMPREGADO(A) DOMESTICO(A)', 'EMPREGADO(A) DOMESTICO(A)'), ('PARENTE DO(A) EMPREGADO(A) DOMESTICO(A)', 'PARENTE DO(A) EMPREGADO(A) DOMESTICO(A)'), ('INDIVIDUAL EM DOMICILIO COLETIVO', 'INDIVIDUAL EM DOMICILIO COLETIVO'), ('OUTRO', 'OUTRA'), ('NO', 'PREFIRO NÃO RESPONDER')], null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='rendimentoBrutoMensalResponsavelDom',
            field=models.CharField(blank=True, choices=[('VALOR EM DINHEIRO, PRODUTOS OU MERCADORIAS', ' VALOR EM DINHEIRO, PRODUTOS OU MERCADORIAS'), ('OUTRA FORMA (MORADIA, ALIMENTAÇÃO, TREINAMENTO ETC.)', 'OUTRA FORMA (MORADIA, ALIMENTAÇÃO, TREINAMENTO ETC.)'), ('NÃO TEM', 'NÃO TEM')], null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='sabeLerEscrever',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='seConsideraIndigena',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='seConsideraQuilombola',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='sexoPessoaFalecida',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO')], null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='sobrenome',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='valorRendimentoBrutoMensal',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='especieDomicilio',
            field=models.CharField(blank=True, choices=[('DOMICILIO PARTICULAR PERMANENTEMENTE OCUPADO', 'DOMICILIO PARTICULAR PERMANENTEMENTE OCUPADO'), ('DOMICILIO PARTICULAR IMPROVISADO OCUPADO', 'DOMICILIO PARTICULAR IMPROVISADO OCUPADO'), ('DOMICILIO COLETIVO COM MORADOR', 'DOMICILIO COLETIVO COM MORADOR')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='municipio',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='tipoDomicilio',
            field=models.CharField(blank=True, choices=[('CASA', 'CASA'), ('CASA DE VILA OU EM CONDOMINIO', 'CASA DE VILA OU EM CONDOMINIO'), ('APARTAMENTO', 'APARTAMENTO'), ('HABITAÇÃO EM CASA DE CÔMODOS OU CORTIÇO', 'HABITAÇÃO EM CASA DE CÔMODOS OU CORTIÇO'), ('HABITAÇÃO INDÍGENA SEM PAREDES OU MALOCA', 'HABITAÇÃO INDÍGENA SEM PAREDES OU MALOCA'), ('ESTRUTURA RESIDENCIAL PERMANENTE DEGRADADA OU INACABADA', 'ESTRUTURA RESIDENCIAL PERMANENTE DEGRADADA OU INACABADA'), ('TENDA OU BARRACA DE LONA, PLÁSTICO OU TECIDO', 'TENDA OU BARRACA DE LONA, PLÁSTICO OU TECIDO'), ('DENTRO DO ESTABELECIMENTO EM FUNCIONAMENTO', 'DENTRO DO ESTABELECIMENTO EM FUNCIONAMENTO'), ('OUTROS (ABRIGOS NATURAIS E OUTRAS ESTRUTURAS IMPROVISADAS', 'OUTROS (ABRIGOS NATURAIS E OUTRAS ESTRUTURAS IMPROVISADAS'), ('ESTRUTURA IMPROVISADA EM LOGRADOURO PÚBLICO,EXCETO TENDA OU BARRACA', 'ESTRUTURA IMPROVISADA EM LOGRADOURO PÚBLICO,EXCETO TENDA OU BARRACA'), ('ESTRUTURA NÃO RESIDENCIAL PERMANENTE DEGRADADA OU INACABADA', 'ESTRUTURA NÃO RESIDENCIAL PERMANENTE DEGRADADA OU INACABADA'), ('VEÍCULOS (CARROS, CAMINHÕES, TRAILERS, BARCOS ETC.)', 'VEÍCULOS (CARROS, CAMINHÕES, TRAILERS, BARCOS ETC.)'), ('ASILO OU OUTRA INSTITUIÇÃO DE LONGA PERMANÊNCIA PARA IDOSOS', 'ASILO OU OUTRA INSTITUIÇÃO DE LONGA PERMANÊNCIA PARA IDOSOS'), ('HOTEL OU PENSÃO', 'HOTEL OU PENSÃO'), ('ALOJAMENTO', 'ALOJAMENTO'), ('PENITENCIÁRIA, CENTRO DE DETENÇÃO E SIMILAR', 'PENITENCIÁRIA, CENTRO DE DETENÇÃO E SIMILAR'), ('ABRIGO', 'ABRIGO'), ('ALBERGUE OU CASA DE PASSAGEM PARA POPULAÇÃO EM SITUAÇÃO DE RUA', 'ALBERGUE OU CASA DE PASSAGEM PARA POPULAÇÃO EM SITUAÇÃO DE RUA'), ('ABRIGO, CASAS DE PASSAGEM OU REPÚBLICA ASSISTENCIAL PARA OUTROS GRUPOS VULNERÁVEIS', 'ABRIGO, CASAS DE PASSAGEM OU REPÚBLICA ASSISTENCIAL PARA OUTROS GRUPOS VULNERÁVEIS'), ('CLÍNICA PSIQUIÁTRICA, COMUNIDADE TERAPÊUTICA E SIMILAR', 'CLÍNICA PSIQUIÁTRICA, COMUNIDADE TERAPÊUTICA E SIMILAR'), ('ORFANATO E SIMILAR', 'ORFANATO E SIMILAR'), ('UNIDADE DE INTERNAÇÃO DE MENORES', 'UNIDADE DE INTERNAÇÃO DE MENORES'), ('QUARTEL OU OUTRA ORGANIZAÇÃO MILITAR', 'QUARTEL OU OUTRA ORGANIZAÇÃO MILITAR'), ('OUTRO', 'OUTRO')], max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='uf',
            field=models.CharField(blank=True, choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')], null=True),
        ),
    ]
