# Generated by Django 5.2.1 on 2025-06-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_delete_administrador_remove_domicilio_distrito_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='morador',
            name='faixaRendimento',
            field=models.CharField(blank=True, choices=[('1,00 A 500,00', '1,00 A 500,00'), ('501,00 A 1.000,00', '501,00 A 1.000,00'), ('1.001,00 A 2.000,00', '1.001,00 A 2.000,00'), ('2.001,00 A 3.000,00', '2.001,00 A 3.000,00'), ('3.001,00 A 5.000,00', '3.001,00 A 5.000,00'), ('5.001,00 A 10.000,00', '5.001,00 A 10.000,00'), ('10.001,00 A 20.000,00', '10.001,00 A 20.000,00'), ('20.001,00 A 100.000', '20.001,00 A 100.000'), ('100.001 OU MAIS', '100.001 OU MAIS')], null=True),
        ),
    ]
