# Generated by Django 5.2 on 2025-05-30 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_administrador_remove_domicilio_seimoradores_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='municipio',
            field=models.CharField(max_length=50),
        ),
    ]
