# Generated by Django 5.2 on 2025-05-30 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_domicilio_municipio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='distrito',
            field=models.CharField(max_length=50),
        ),
    ]
