# Generated by Django 5.2 on 2025-05-30 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_domicilio_distrito'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
