# Generated by Django 5.2 on 2025-05-30 18:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_domicilio_nome'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='domicilio',
            name='nome',
        ),
    ]
