# Generated by Django 5.2.1 on 2025-05-30 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_remove_domicilio_nome'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='qtdCriancas',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='qtdMoradores',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
