# Generated by Django 5.2.1 on 2025-05-30 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_morador_qtdcriancas_morador_qtdmoradores'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='dtNascimento',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='sobrenomeMorador',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
