# Generated by Django 5.2.1 on 2025-05-30 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_morador_dtnascimento_morador_sobrenomemorador'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='morador',
            name='qtdCriancas',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='qtdMoradores',
        ),
        migrations.AddField(
            model_name='domicilio',
            name='qtdCriancas',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='qtdMoradores',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
    ]
