# Generated by Django 5.2.1 on 2025-05-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_remove_morador_qtdcriancas_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='NaoseiMesAno',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='anoNascimento',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='idadeEmAnos',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='idadeEmMeses',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='idadeMorador',
            field=models.CharField(blank=True, choices=[('UM ANO OU MAIS', 'UM ANO OU MAIS'), ('MENOS DE UM ANO', 'MENOS DE UM ANO')], null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='mesNascimento',
            field=models.CharField(blank=True, choices=[('JANEIRO', 'JANEIRO'), ('FEVEREIRO', 'FEVEREIRO'), ('MARCO', 'MARCO'), ('ABRIL', 'ABRIL'), ('MAIO', 'MAIO'), ('JUNHO', 'JUNHO'), ('JULHO', 'JULHO'), ('AGOSTO', 'AGOSTO'), ('SETEMBRO', 'SETEMBRO'), ('OUTUBRO', 'OUTUBRO'), ('NOVEMBRO', 'NOVEMBRO'), ('DEZEMBRO', 'DEZEMBRO')], null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='relacaoConvivencia',
            field=models.CharField(blank=True, choices=[('PESSOA RESPONSAVEL PELO DOMICILIO', 'PESSOA RESPONSAVEL PELO DOMICILIO'), ('CONJUGE OU COMPANHEIRO(A) DE SEXO DIFERENTE', 'CONJUGE OU COMPANHEIRO(A) DE SEXO DIFERENTE'), ('CONJUGE OU COMPANHEIRO(A) DO MESMO SEXO', 'CONJUGUE OU COMPANHEIRO(A) DO MESMO SEXO'), ('FILHO(A) DO RESPONSAVEL E DO CONJUGE', 'FILHO(A) DO RESPONSAVEL E DO CONJUGE'), ('FILHO(A) SOMENTE DO RESPONSAVEL', 'FILHO(A) SOMENTE DO RESPONSAVEL'), ('ENTEADO(A)', 'ENTEADO(A)'), ('GENRO OU NORA', 'GENRO OU NORA'), ('PAI, MAE, PADRASTO OU MADRASTA', 'PAI, MAE, PADRASTO OU MADRASTA'), ('SOGRO(A)', 'SOGRO(A)'), ('NETO(A)', 'NETO(A)'), ('BISNETO(A)', 'BISNETO(A)'), ('IRMAO OU IRMA', 'IRMAO OU IRMA'), ('AVO OU AVO', 'AVO OU AVO'), ('OUTRO PARENTE', 'OUTRO PARENTE'), ('AGREGADO(A)', 'AGREGADO(A)'), ('CONVIVENTE', 'CONVIVENTE'), ('PENSIONISTA', 'PENSIONISTA'), ('EMPREGADO(A) DOMESTICO(A)', 'EMPREGADO(A) DOMESTICO(A)'), ('PARENTE DO(A) EMPREGADO(A) DOMESTICO(A)', 'PARENTE DO(A) EMPREGADO(A) DOMESTICO(A)'), ('INDIVIDUAL EM DOMICILIO COLETIVO', 'INDIVIDUAL EM DOMICILIO COLETIVO')], null=True),
        ),
        migrations.AddField(
            model_name='morador',
            name='sexoMorador',
            field=models.CharField(blank=True, choices=[('MASCULINO', 'MASCULINO'), ('FEMININO', 'FEMININO')], null=True),
        ),
    ]
