# Generated by Django 5.2.1 on 2025-06-06 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_caracteristicasdomicilio'),
    ]

    operations = [
        migrations.RenameField(
            model_name='caracteristicasdomicilio',
            old_name='banheirosUsoExclusivo',
            new_name='quantosbanheirosUsoExclusivo',
        ),
        migrations.RenameField(
            model_name='caracteristicasdomicilio',
            old_name='banheiroUsoComumMais',
            new_name='utilizaBanheiroUsoComumMais',
        ),
    ]
