# Generated by Django 5.2 on 2025-06-06 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0013_rename_banheirosusoexclusivo_caracteristicasdomicilio_quantosbanheirosusoexclusivo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='caracteristicasdomicilio',
            name='domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Domicilios', to='app.domicilio'),
        ),
    ]
