# Generated by Django 5.2 on 2025-06-06 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_caracteristicasdomicilio_domicilio'),
    ]

    operations = [
        migrations.AddField(
            model_name='domicilio',
            name='abastecimentoAgua',
            field=models.CharField(blank=True, choices=[('REDE GERAL DE DISTRIBUIÇÃO', 'REDE GERAL DE DISTRIBUIÇÃO'), ('POÇO PROFUNDO OU ARTESIANO', 'POÇO PROFUNDO OU ARTESIANO'), ('POÇO RASO, FREÁTICO OU CACIMBA', 'POÇO RASO, FREÁTICO OU CACIMBA'), ('FONTE, NASCENTE OU MINA', 'FONTE, NASCENTE OU MINA'), ('CARRO-PIPA', 'CARRO-PIPA'), ('ÁGUA DA CHUVA ARMAZENADA', 'ÁGUA DA CHUVA ARMAZENADA'), ('RIOS, AÇUDES, CÓRREGOS, LAGOS E IGARAPÉS', 'RIOS, AÇUDES, CÓRREGOS, LAGOS E IGARAPÉS'), ('OUTRA', 'OUTRA')], null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='acessoRedeAgua',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='aguaChega',
            field=models.CharField(blank=True, choices=[('ENCANADA ATÉ DENTRO DA CASA, APARTAMENTO OU HABITAÇÃO', 'ENCANADA ATÉ DENTRO DA CASA, APARTAMENTO OU HABITAÇÃO'), ('ENCANADA, MAS APENAS NO TERRENO', 'ENCANADA, MAS APENAS NO TERRENO'), ('NÃO CHEGA ENCANADA', 'NÃO CHEGA ENCANADA')], null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='esgotoFim',
            field=models.CharField(blank=True, choices=[('REDE GERAL OU PLUVIAL', 'REDE GERAL OU PLUVIAL'), ('FOSSA SÉPTICA OU FOSSA FILTRO LIGADA À REDE', 'FOSSA SÉPTICA OU FOSSA FILTRO LIGADA À REDE'), ('FOSSA SÉPTICA OU FOSSA FILTRO NÃO LIGADA À REDE', 'FOSSA SÉPTICA OU FOSSA FILTRO NÃO LIGADA À REDE'), ('FOSSA RUDIMENTAR OU BURACO', 'FOSSA RUDIMENTAR OU BURACO'), ('VALA', 'VALA'), ('RIO, LAGO, CÓRREGO OU MAR', 'RIO, LAGO, CÓRREGO OU MAR'), ('OUTRA FORMA', 'OUTRA FORMA')], null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='esgotoSBFim',
            field=models.CharField(blank=True, choices=[('REDE GERAL OU PLUVIAL', 'REDE GERAL OU PLUVIAL'), ('FOSSA SÉPTICA OU FOSSA FILTRO LIGADA À REDE', 'FOSSA SÉPTICA OU FOSSA FILTRO LIGADA À REDE'), ('FOSSA SÉPTICA OU FOSSA FILTRO NÃO LIGADA À REDE', 'FOSSA SÉPTICA OU FOSSA FILTRO NÃO LIGADA À REDE'), ('FOSSA RUDIMENTAR OU BURACO', 'FOSSA RUDIMENTAR OU BURACO'), ('VALA', 'VALA'), ('RIO, LAGO, CÓRREGO OU MAR', 'RIO, LAGO, CÓRREGO OU MAR'), ('OUTRA FORMA', 'OUTRA FORMA')], null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='lixoDomicilio',
            field=models.CharField(blank=True, choices=[('COLETADO NO DOMICÍLIO POR SERVIÇO DE LIMPEZA', 'COLETADO NO DOMICÍLIO POR SERVIÇO DE LIMPEZA'), ('DEPOSITADO EM CAÇAMBA DE SERVIÇO DE LIMPEZA', 'DEPOSITADO EM CAÇAMBA DE SERVIÇO DE LIMPEZA'), ('QUEIMADO NA PROPRIEDADE', 'QUEIMADO NA PROPRIEDADE'), ('ENTERRADO NA PROPRIEDADE', 'ENTERRADO NA PROPRIEDADE'), ('JOGADO EM TERRENO BALDIO, ENCOSTA OU ÁREA PÚBLICA', 'JOGADO EM TERRENO BALDIO, ENCOSTA OU ÁREA PÚBLICA'), ('OUTRO DESTINO', 'OUTRO DESTINO')], null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='quantosbanheirosUsoExclusivo',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='utilizaBanheiroUsoComumMais',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='domicilio',
            name='utilizaSanitarioBuracoDejecoes',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='CaracteristicasDomicilio',
        ),
    ]
