# Generated by Django 5.2 on 2025-06-06 17:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_domicilio_abastecimentoagua_domicilio_acessoredeagua_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='morador',
            name='domicilio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Morador', to='app.domicilio'),
        ),
    ]
