# Generated by Django 5.2.1 on 2025-06-06 19:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_domicilio_cep'),
    ]

    operations = [
        migrations.RenameField(
            model_name='morador',
            old_name='sobrenomeMorador',
            new_name='sobrenome',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='NaoseiMesAno',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='anoNascimento',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='dtNascimento',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='idadeEmAnos',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='idadeEmMeses',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='idadeMorador',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='mesNascimento',
        ),
        migrations.RemoveField(
            model_name='morador',
            name='sexoMorador',
        ),
        migrations.AddField(
            model_name='morador',
            name='data_Nascimento',
            field=models.DateField(default='2025-06-06', max_length=2),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='cep',
            field=models.CharField(max_length=9),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='especieDomicilio',
            field=models.CharField(choices=[('DOMICILIO PARTICULAR PERMANENTEMENTE OCUPADO', 'DOMICILIO PARTICULAR PERMANENTEMENTE OCUPADO'), ('DOMICILIO PARTICULAR IMPROVISADO OCUPADO', 'DOMICILIO PARTICULAR IMPROVISADO OCUPADO'), ('DOMICILIO COLETIVO COM MORADOR', 'DOMICILIO COLETIVO COM MORADOR')], default='OUTROS', max_length=100),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='qtdCriancas',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='qtdMoradores',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='quantosbanheirosUsoExclusivo',
            field=models.PositiveSmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='tipoDomicilio',
            field=models.CharField(choices=[('CASA', 'CASA'), ('CASA DE VILA OU EM CONDOMINIO', 'CASA DE VILA OU EM CONDOMINIO'), ('APARTAMENTO', 'APARTAMENTO'), ('HABITAÇÃO EM CASA DE CÔMODOS OU CORTIÇO', 'HABITAÇÃO EM CASA DE CÔMODOS OU CORTIÇO'), ('HABITAÇÃO INDÍGENA SEM PAREDES OU MALOCA', 'HABITAÇÃO INDÍGENA SEM PAREDES OU MALOCA'), ('ESTRUTURA RESIDENCIAL PERMANENTE DEGRADADA OU INACABADA', 'ESTRUTURA RESIDENCIAL PERMANENTE DEGRADADA OU INACABADA'), ('TENDA OU BARRACA DE LONA, PLÁSTICO OU TECIDO', 'TENDA OU BARRACA DE LONA, PLÁSTICO OU TECIDO'), ('DENTRO DO ESTABELECIMENTO EM FUNCIONAMENTO', 'DENTRO DO ESTABELECIMENTO EM FUNCIONAMENTO'), ('OUTROS (ABRIGOS NATURAIS E OUTRAS ESTRUTURAS IMPROVISADAS', 'OUTROS (ABRIGOS NATURAIS E OUTRAS ESTRUTURAS IMPROVISADAS'), ('ESTRUTURA IMPROVISADA EM LOGRADOURO PÚBLICO,EXCETO TENDA OU BARRACA', 'ESTRUTURA IMPROVISADA EM LOGRADOURO PÚBLICO,EXCETO TENDA OU BARRACA'), ('ESTRUTURA NÃO RESIDENCIAL PERMANENTE DEGRADADA OU INACABADA', 'ESTRUTURA NÃO RESIDENCIAL PERMANENTE DEGRADADA OU INACABADA'), ('VEÍCULOS (CARROS, CAMINHÕES, TRAILERS, BARCOS ETC.)', 'VEÍCULOS (CARROS, CAMINHÕES, TRAILERS, BARCOS ETC.)'), ('ASILO OU OUTRA INSTITUIÇÃO DE LONGA PERMANÊNCIA PARA IDOSOS', 'ASILO OU OUTRA INSTITUIÇÃO DE LONGA PERMANÊNCIA PARA IDOSOS'), ('HOTEL OU PENSÃO', 'HOTEL OU PENSÃO'), ('ALOJAMENTO', 'ALOJAMENTO'), ('PENITENCIÁRIA, CENTRO DE DETENÇÃO E SIMILAR', 'PENITENCIÁRIA, CENTRO DE DETENÇÃO E SIMILAR'), ('ABRIGO', 'ABRIGO'), ('ALBERGUE OU CASA DE PASSAGEM PARA POPULAÇÃO EM SITUAÇÃO DE RUA', 'ALBERGUE OU CASA DE PASSAGEM PARA POPULAÇÃO EM SITUAÇÃO DE RUA'), ('ABRIGO, CASAS DE PASSAGEM OU REPÚBLICA ASSISTENCIAL PARA OUTROS GRUPOS VULNERÁVEIS', 'ABRIGO, CASAS DE PASSAGEM OU REPÚBLICA ASSISTENCIAL PARA OUTROS GRUPOS VULNERÁVEIS'), ('CLÍNICA PSIQUIÁTRICA, COMUNIDADE TERAPÊUTICA E SIMILAR', 'CLÍNICA PSIQUIÁTRICA, COMUNIDADE TERAPÊUTICA E SIMILAR'), ('ORFANATO E SIMILAR', 'ORFANATO E SIMILAR'), ('UNIDADE DE INTERNAÇÃO DE MENORES', 'UNIDADE DE INTERNAÇÃO DE MENORES'), ('QUARTEL OU OUTRA ORGANIZAÇÃO MILITAR', 'QUARTEL OU OUTRA ORGANIZAÇÃO MILITAR'), ('OUTRO', 'OUTRO')], max_length=100),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='uf',
            field=models.CharField(choices=[('AC', 'Acre'), ('AL', 'Alagoas'), ('AP', 'Amapá'), ('AM', 'Amazonas'), ('BA', 'Bahia'), ('CE', 'Ceará'), ('DF', 'Distrito Federal'), ('ES', 'Espírito Santo'), ('GO', 'Goiás'), ('MA', 'Maranhão'), ('MT', 'Mato Grosso'), ('MS', 'Mato Grosso do Sul'), ('MG', 'Minas Gerais'), ('PA', 'Pará'), ('PB', 'Paraíba'), ('PR', 'Paraná'), ('PE', 'Pernambuco'), ('PI', 'Piauí'), ('RJ', 'Rio de Janeiro'), ('RN', 'Rio Grande do Norte'), ('RS', 'Rio Grande do Sul'), ('RO', 'Rondônia'), ('RR', 'Roraima'), ('SC', 'Santa Catarina'), ('SP', 'São Paulo'), ('SE', 'Sergipe'), ('TO', 'Tocantins')]),
        ),
        migrations.AlterField(
            model_name='morador',
            name='nome',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='morador',
            name='relacaoConvivencia',
            field=models.CharField(choices=[('PESSOA RESPONSAVEL PELO DOMICILIO', 'PESSOA RESPONSAVEL PELO DOMICILIO'), ('CONJUGE OU COMPANHEIRO(A) DE SEXO DIFERENTE', 'CONJUGE OU COMPANHEIRO(A) DE SEXO DIFERENTE'), ('CONJUGE OU COMPANHEIRO(A) DO MESMO SEXO', 'CONJUGUE OU COMPANHEIRO(A) DO MESMO SEXO'), ('FILHO(A) DO RESPONSAVEL E DO CONJUGE', 'FILHO(A) DO RESPONSAVEL E DO CONJUGE'), ('FILHO(A) SOMENTE DO RESPONSAVEL', 'FILHO(A) SOMENTE DO RESPONSAVEL'), ('ENTEADO(A)', 'ENTEADO(A)'), ('GENRO OU NORA', 'GENRO OU NORA'), ('PAI, MAE, PADRASTO OU MADRASTA', 'PAI, MAE, PADRASTO OU MADRASTA'), ('SOGRO(A)', 'SOGRO(A)'), ('NETO(A)', 'NETO(A)'), ('BISNETO(A)', 'BISNETO(A)'), ('IRMAO OU IRMA', 'IRMAO OU IRMA'), ('AVO OU AVO', 'AVO OU AVO'), ('OUTRO PARENTE', 'OUTRO PARENTE'), ('AGREGADO(A)', 'AGREGADO(A)'), ('CONVIVENTE', 'CONVIVENTE'), ('PENSIONISTA', 'PENSIONISTA'), ('EMPREGADO(A) DOMESTICO(A)', 'EMPREGADO(A) DOMESTICO(A)'), ('PARENTE DO(A) EMPREGADO(A) DOMESTICO(A)', 'PARENTE DO(A) EMPREGADO(A) DOMESTICO(A)'), ('INDIVIDUAL EM DOMICILIO COLETIVO', 'INDIVIDUAL EM DOMICILIO COLETIVO'), ('OUTRO', 'OUTRA'), ('NO', 'PREFIRO NÃO RESPONDER')]),
        ),
    ]
