# Generated by Django 5.2.3 on 2025-06-11 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_rename_sobrenomemorador_morador_sobrenome_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domicilio',
            name='cep',
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='especieDomicilio',
            field=models.CharField(choices=[('DOMICILIO PARTICULAR PERMANENTEMENTE OCUPADO', 'DOMICILIO PARTICULAR PERMANENTEMENTE OCUPADO'), ('DOMICILIO PARTICULAR IMPROVISADO OCUPADO', 'DOMICILIO PARTICULAR IMPROVISADO OCUPADO'), ('DOMICILIO COLETIVO COM MORADOR', 'DOMICILIO COLETIVO COM MORADOR')], max_length=100),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='qtdCriancas',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='qtdMoradores',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='domicilio',
            name='quantosbanheirosUsoExclusivo',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='morador',
            name='data_Nascimento',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='morador',
            name='nome',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
