# Generated by Django 5.2.3 on 2025-06-11 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0019_alter_domicilio_cep_alter_domicilio_especiedomicilio_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='domicilio',
            old_name='distrito',
            new_name='cidade',
        ),
        migrations.RemoveField(
            model_name='domicilio',
            name='municipio',
        ),
    ]
